-- Curricular analysis module. GENERATED by scripts/curricular-schema.mjs from web/prisma/schema.prisma.
-- Do not edit by hand: change the Prisma schema, rerun the script and then `npm run db:sync`.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "curricular";

-- CreateEnum
CREATE TYPE "curricular"."Role" AS ENUM ('ADMIN', 'ACADEMIC_COORDINATOR', 'TUTOR', 'ANALYST', 'VIEWER', 'STUDENT');

-- CreateEnum
CREATE TYPE "curricular"."AnalysisStatus" AS ENUM ('UPLOADED', 'PARSING', 'AI_EXTRACTION', 'NORMALIZING', 'CALCULATING', 'VALIDATING', 'AI_AUDIT', 'WAITING_REVIEW', 'COMPLETED', 'FAILED', 'AI_ERROR');

-- CreateEnum
CREATE TYPE "curricular"."SubjectStatus" AS ENUM ('EXEMPTED', 'PENDING', 'REVIEW');

-- CreateEnum
CREATE TYPE "curricular"."Readability" AS ENUM ('CLEAR', 'UNCLEAR', 'UNREADABLE');

-- CreateEnum
CREATE TYPE "curricular"."SubjectOrigin" AS ENUM ('AI', 'USER');

-- CreateEnum
CREATE TYPE "curricular"."EntryPeriodSource" AS ENUM ('DOCUMENT', 'STRUCTURED', 'RULE', 'USER');

-- CreateEnum
CREATE TYPE "curricular"."ReliabilityLevel" AS ENUM ('HIGH', 'REVIEW_RECOMMENDED', 'REVIEW_REQUIRED');

-- CreateEnum
CREATE TYPE "curricular"."ProjectionSubjectKind" AS ENUM ('REGULAR', 'BACKLOG');

-- CreateEnum
CREATE TYPE "curricular"."WarningSeverity" AS ENUM ('INFO', 'WARNING', 'CRITICAL');

-- CreateEnum
CREATE TYPE "curricular"."WarningSource" AS ENUM ('PIPELINE', 'VALIDATOR', 'AUDITOR', 'EXTRACTION');

-- CreateEnum
CREATE TYPE "curricular"."AIOperation" AS ENUM ('DOCUMENT_EXTRACTION', 'CURRICULUM_EXTRACTION', 'AUDIT', 'FINAL_EXPLANATION', 'CONNECTION_TEST');

-- CreateEnum
CREATE TYPE "curricular"."EnrollmentStatus" AS ENUM ('PENDING', 'ENROLLED', 'NOT_ENROLLED');

-- CreateEnum
CREATE TYPE "curricular"."FollowUpCadence" AS ENUM ('ONCE_DAILY', 'TWICE_DAILY');

-- CreateEnum
CREATE TYPE "curricular"."CourseFormat" AS ENUM ('EAD_DIGITAL', 'SEMIPRESENCIAL');

-- CreateEnum
CREATE TYPE "curricular"."AIReviewStatus" AS ENUM ('OK', 'REVIEW');

-- CreateEnum
CREATE TYPE "curricular"."IntegrationStatus" AS ENUM ('DISCONNECTED', 'CONNECTED', 'ERROR');

-- CreateEnum
CREATE TYPE "curricular"."RuleStatus" AS ENUM ('CONFIRMED', 'CONFIGURABLE', 'NOT_CONFIGURED');

-- CreateEnum
CREATE TYPE "curricular"."RetentionPolicy" AS ENUM ('DAYS_30', 'DAYS_90', 'DAYS_180', 'INDEFINITE', 'DELETE_AFTER_PROCESSING');

-- CreateEnum
CREATE TYPE "curricular"."AIPrivacyMode" AS ENUM ('PDF_FILE', 'REDACTED_TEXT');

-- CreateEnum
CREATE TYPE "curricular"."DeletionRequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "curricular"."AcademicGridReviewStatus" AS ENUM ('NO_PENDING', 'CAN_ADD', 'NEAR_LIMIT', 'LIMIT_REACHED', 'MANUAL_REVIEW_REQUIRED');

-- CreateEnum
CREATE TYPE "curricular"."AcademicDocumentType" AS ENUM ('OFFICIAL_ACADEMIC_HISTORY', 'SIMPLE_ACADEMIC_HISTORY', 'CURRICULAR_EXTRACT', 'UNKNOWN_ACADEMIC_DOCUMENT');

-- CreateEnum
CREATE TYPE "curricular"."AcademicRequestStatus" AS ENUM ('RECEIVED', 'PROCESSING', 'UNDER_REVIEW', 'WAITING_NEW_DOCUMENT', 'NO_CHANGES', 'COMPLETED', 'REJECTED', 'FAILED');

-- CreateTable
CREATE TABLE "curricular"."User" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "authUserId" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" "curricular"."Role" NOT NULL DEFAULT 'ANALYST',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "poloCode" TEXT,
    "phone" TEXT,
    "followUpEmailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "followUpPushEnabled" BOOLEAN NOT NULL DEFAULT true,
    "followUpRepeatBusinessDays" INTEGER NOT NULL DEFAULT 1,
    "followUpMaxReminders" INTEGER NOT NULL DEFAULT 5,
    "followUpBusinessStartHour" INTEGER,
    "followUpBusinessEndHour" INTEGER,
    "followUpCadence" "curricular"."FollowUpCadence",
    "followUpPreferencesConfirmedAt" TIMESTAMPTZ(6),
    "lastLoginAt" TIMESTAMPTZ(6),
    "lastActiveAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AuditLog" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "userId" UUID,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "metadata" JSONB,
    "ip" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."CurricularAnalysis" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "status" "curricular"."AnalysisStatus" NOT NULL DEFAULT 'UPLOADED',
    "createdById" UUID NOT NULL,
    "courseName" TEXT,
    "matrixLabel" TEXT,
    "campus" TEXT,
    "modality" TEXT,
    "candidateLabel" TEXT,
    "studentName" TEXT,
    "poloCode" TEXT,
    "poloName" TEXT,
    "courseFormat" "curricular"."CourseFormat",
    "reanalysisOfId" UUID,
    "enrollmentStatus" "curricular"."EnrollmentStatus" NOT NULL DEFAULT 'PENDING',
    "enrollmentUpdatedAt" TIMESTAMPTZ(6),
    "enrollmentUpdatedById" UUID,
    "enrollmentNote" TEXT,
    "enrollmentReanalysisAt" TIMESTAMPTZ(6),
    "followUpDueAt" TIMESTAMPTZ(6),
    "followUpNotifiedAt" TIMESTAMPTZ(6),
    "followUpNotificationCount" INTEGER NOT NULL DEFAULT 0,
    "entryPeriod" INTEGER,
    "entryPeriodSource" "curricular"."EntryPeriodSource",
    "entryTerm" TEXT,
    "startTerm" TEXT NOT NULL,
    "reliability" "curricular"."ReliabilityLevel",
    "reviewItemsCount" INTEGER NOT NULL DEFAULT 0,
    "processingSteps" JSONB NOT NULL DEFAULT '[]',
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "ruleSetVersionId" UUID NOT NULL,
    "engineVersion" TEXT NOT NULL,
    "extractorPromptVersion" TEXT,
    "auditorPromptVersion" TEXT,
    "extractionModel" TEXT,
    "auditModel" TEXT,
    "projectionIncomplete" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" TIMESTAMPTZ(6),
    "lastCalculatedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "CurricularAnalysis_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."PushSubscription" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "endpoint" TEXT NOT NULL,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "userAgent" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUsedAt" TIMESTAMPTZ(6),

    CONSTRAINT "PushSubscription_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AnalysisDeletionRequest" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "requestedById" UUID NOT NULL,
    "status" "curricular"."DeletionRequestStatus" NOT NULL DEFAULT 'PENDING',
    "reason" TEXT,
    "reviewedById" UUID,
    "reviewedAt" TIMESTAMPTZ(6),
    "decisionNote" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "AnalysisDeletionRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."UploadedDocument" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "originalName" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "sha256" TEXT NOT NULL,
    "pageCount" INTEGER,
    "mimeType" TEXT NOT NULL,
    "localExtraction" JSONB,
    "deleteAfter" TIMESTAMPTZ(6),
    "deletedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UploadedDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AnalyzedSubject" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "rowHash" TEXT NOT NULL,
    "code" TEXT,
    "name" TEXT NOT NULL,
    "workload" INTEGER NOT NULL,
    "period" INTEGER NOT NULL,
    "usedSubject" TEXT,
    "status" "curricular"."SubjectStatus" NOT NULL,
    "readability" "curricular"."Readability" NOT NULL DEFAULT 'CLEAR',
    "sourcePage" INTEGER NOT NULL,
    "sourceRow" INTEGER NOT NULL,
    "bbox" JSONB,
    "origin" "curricular"."SubjectOrigin" NOT NULL DEFAULT 'AI',
    "note" TEXT,
    "sortIndex" INTEGER NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "AnalyzedSubject_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."SemesterProjection" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "index" INTEGER NOT NULL,
    "term" TEXT NOT NULL,
    "periodNumber" INTEGER,
    "isAdditional" BOOLEAN NOT NULL DEFAULT false,
    "subjectsInPeriod" INTEGER NOT NULL,
    "exemptedInPeriod" INTEGER NOT NULL,
    "regularSubjectsToTake" INTEGER NOT NULL,
    "maximumCapacity" INTEGER NOT NULL,
    "backlogCapacity" INTEGER NOT NULL,
    "subjectsFromBacklog" INTEGER NOT NULL,
    "semesterLoad" INTEGER NOT NULL,
    "remainingBacklog" INTEGER NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SemesterProjection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."ProjectionSubject" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "projectionId" UUID NOT NULL,
    "subjectId" UUID NOT NULL,
    "kind" "curricular"."ProjectionSubjectKind" NOT NULL,
    "order" INTEGER NOT NULL,

    CONSTRAINT "ProjectionSubject_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."DocumentClaim" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "value" DOUBLE PRECISION,
    "sourcePage" INTEGER NOT NULL,
    "rawText" TEXT,
    "calculatedValue" DOUBLE PRECISION,
    "matches" BOOLEAN,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DocumentClaim_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AnalysisWarning" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "severity" "curricular"."WarningSeverity" NOT NULL,
    "source" "curricular"."WarningSource" NOT NULL,
    "message" TEXT NOT NULL,
    "subjectId" UUID,
    "sourcePage" INTEGER,
    "data" JSONB,
    "resolvedAt" TIMESTAMPTZ(6),
    "resolvedById" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AnalysisWarning_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."ManualCorrection" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "subjectId" UUID,
    "userId" UUID NOT NULL,
    "field" TEXT NOT NULL,
    "previousValue" TEXT,
    "newValue" TEXT,
    "reason" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ManualCorrection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AIExtraction" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "model" TEXT NOT NULL,
    "promptVersion" TEXT NOT NULL,
    "privacyMode" "curricular"."AIPrivacyMode" NOT NULL,
    "rawOutput" JSONB,
    "durationMs" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    "errorCode" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AIExtraction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AIReview" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID NOT NULL,
    "model" TEXT NOT NULL,
    "promptVersion" TEXT NOT NULL,
    "status" "curricular"."AIReviewStatus" NOT NULL,
    "issues" JSONB NOT NULL,
    "durationMs" INTEGER NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AIReview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AIUsage" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "analysisId" UUID,
    "operation" "curricular"."AIOperation" NOT NULL,
    "model" TEXT NOT NULL,
    "inputTokens" INTEGER NOT NULL,
    "outputTokens" INTEGER NOT NULL,
    "totalTokens" INTEGER NOT NULL,
    "estimatedCost" DECIMAL(12,6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AIUsage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."OpenAIIntegration" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "status" "curricular"."IntegrationStatus" NOT NULL DEFAULT 'DISCONNECTED',
    "encryptedApiKey" TEXT,
    "encryptionIv" TEXT,
    "encryptionAuthTag" TEXT,
    "keyVersion" INTEGER,
    "apiKeyLastFour" TEXT,
    "extractionModel" TEXT NOT NULL DEFAULT 'gpt-5.6-sol',
    "auditModel" TEXT NOT NULL DEFAULT 'gpt-5.6-sol',
    "futureExplanationModel" TEXT,
    "projectLabel" TEXT,
    "serviceAccountLabel" TEXT,
    "lastTestedAt" TIMESTAMPTZ(6),
    "lastConnectionStatus" TEXT,
    "lastErrorCode" TEXT,
    "createdById" UUID,
    "updatedById" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "OpenAIIntegration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."RuleSetVersion" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "version" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT false,
    "effectiveFrom" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,
    "createdById" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RuleSetVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."SystemRule" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "ruleSetVersionId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "valueType" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "status" "curricular"."RuleStatus" NOT NULL,
    "description" TEXT NOT NULL,

    CONSTRAINT "SystemRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."SystemSetting" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "SystemSetting_pkey" PRIMARY KEY ("organizationId","key")
);

-- CreateTable
CREATE TABLE "curricular"."CommercialGrade" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "courseName" TEXT NOT NULL,
    "modality" TEXT,
    "curriculumTerm" TEXT,
    "degree" TEXT,
    "knowledgeArea" TEXT,
    "durationSemesters" INTEGER,
    "courseTracks" JSONB,
    "contentHash" CHAR(64),
    "catalogKey" CHAR(64),
    "internshipInfo" TEXT,
    "hasTcc" BOOLEAN NOT NULL DEFAULT false,
    "totalInternshipHours" INTEGER,
    "totalCourseHours" INTEGER,
    "whatsappSummary" TEXT,
    "originalName" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "uploadedById" UUID NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "CommercialGrade_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AcademicGridReview" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "createdById" UUID NOT NULL,
    "studentName" TEXT,
    "rgm" TEXT,
    "courseName" TEXT,
    "currentPeriod" INTEGER,
    "currentPeriodRaw" TEXT,
    "currentPeriodConfirmed" BOOLEAN NOT NULL DEFAULT false,
    "sourceFilename" TEXT NOT NULL,
    "sourceSha256" CHAR(64) NOT NULL,
    "sourcePageCount" INTEGER NOT NULL,
    "status" "curricular"."AcademicGridReviewStatus" NOT NULL DEFAULT 'MANUAL_REVIEW_REQUIRED',
    "snapshot" JSONB NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "completedAt" TIMESTAMPTZ(6),
    "enrollmentId" UUID,

    CONSTRAINT "AcademicGridReview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AcademicGridCorrection" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "reviewId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "disciplineIndex" INTEGER,
    "field" TEXT NOT NULL,
    "previousValue" JSONB,
    "newValue" JSONB,
    "reason" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AcademicGridCorrection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."StudentEnrollment" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "rgm" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "courseName" TEXT,
    "studentUserId" UUID,
    "ownerId" UUID NOT NULL,
    "poloCode" TEXT,
    "currentVersionId" UUID,
    "welcomedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "StudentEnrollment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."StudentDeletionRequest" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "enrollmentId" UUID,
    "studentName" TEXT NOT NULL,
    "rgm" TEXT NOT NULL,
    "requestedById" UUID NOT NULL,
    "reason" TEXT,
    "status" "curricular"."DeletionRequestStatus" NOT NULL DEFAULT 'PENDING',
    "reviewedById" UUID,
    "reviewedAt" TIMESTAMPTZ(6),
    "decisionNote" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "StudentDeletionRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AcademicAnalysisVersion" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "enrollmentId" UUID NOT NULL,
    "reviewId" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "previousVersionId" UUID,
    "preferredSourceId" UUID,
    "academicSnapshotHash" CHAR(64) NOT NULL,
    "snapshot" JSONB NOT NULL,
    "actorUserId" UUID NOT NULL,
    "actorRole" "curricular"."Role" NOT NULL,
    "origin" TEXT NOT NULL,
    "changeSummary" JSONB NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AcademicAnalysisVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AcademicAnalysisSource" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "enrollmentId" UUID NOT NULL,
    "sourceFileHash" CHAR(64) NOT NULL,
    "documentType" "curricular"."AcademicDocumentType" NOT NULL DEFAULT 'CURRICULAR_EXTRACT',
    "parsedSnapshot" JSONB,
    "parserName" TEXT,
    "validationResult" TEXT,
    "normalizedContentHash" CHAR(64),
    "deleteAfter" TIMESTAMPTZ(6),
    "deletedAt" TIMESTAMPTZ(6),
    "storageKey" TEXT,
    "filename" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PROCESSING',
    "stage" TEXT NOT NULL DEFAULT 'Processando extrato',
    "actorUserId" UUID NOT NULL,
    "actorRole" "curricular"."Role" NOT NULL,
    "versionId" UUID,
    "errorMessage" TEXT,
    "reused" BOOLEAN NOT NULL DEFAULT false,
    "attempts" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "AcademicAnalysisSource_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "curricular"."AcademicRequest" (
    "organizationId" UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    "id" UUID NOT NULL,
    "protocol" SERIAL NOT NULL,
    "sourceDocumentId" UUID NOT NULL,
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "previousRequestId" UUID,
    "status" "curricular"."AcademicRequestStatus" NOT NULL DEFAULT 'RECEIVED',
    "actorUserId" UUID NOT NULL,
    "actorRole" "curricular"."Role" NOT NULL,
    "result" TEXT,
    "aiUsed" BOOLEAN NOT NULL DEFAULT false,
    "createdVersion" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "AcademicRequest_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_organizationId_authUserId_key" ON "curricular"."User"("organizationId", "authUserId");

-- CreateIndex
CREATE UNIQUE INDEX "User_organizationId_email_key" ON "curricular"."User"("organizationId", "email");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "curricular"."AuditLog"("createdAt" DESC);

-- CreateIndex
CREATE INDEX "AuditLog_entityType_entityId_idx" ON "curricular"."AuditLog"("entityType", "entityId");

-- CreateIndex
CREATE INDEX "AuditLog_userId_idx" ON "curricular"."AuditLog"("userId");

-- CreateIndex
CREATE INDEX "AuditLog_organizationId_idx" ON "curricular"."AuditLog"("organizationId");

-- CreateIndex
CREATE INDEX "CurricularAnalysis_status_createdAt_idx" ON "curricular"."CurricularAnalysis"("status", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "CurricularAnalysis_createdById_idx" ON "curricular"."CurricularAnalysis"("createdById");

-- CreateIndex
CREATE INDEX "CurricularAnalysis_poloCode_idx" ON "curricular"."CurricularAnalysis"("poloCode");

-- CreateIndex
CREATE INDEX "CurricularAnalysis_enrollmentStatus_followUpDueAt_idx" ON "curricular"."CurricularAnalysis"("enrollmentStatus", "followUpDueAt");

-- CreateIndex
CREATE INDEX "CurricularAnalysis_reanalysisOfId_idx" ON "curricular"."CurricularAnalysis"("reanalysisOfId");

-- CreateIndex
CREATE INDEX "CurricularAnalysis_organizationId_idx" ON "curricular"."CurricularAnalysis"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "PushSubscription_endpoint_key" ON "curricular"."PushSubscription"("endpoint");

-- CreateIndex
CREATE INDEX "PushSubscription_userId_idx" ON "curricular"."PushSubscription"("userId");

-- CreateIndex
CREATE INDEX "PushSubscription_organizationId_idx" ON "curricular"."PushSubscription"("organizationId");

-- CreateIndex
CREATE INDEX "AnalysisDeletionRequest_status_createdAt_idx" ON "curricular"."AnalysisDeletionRequest"("status", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AnalysisDeletionRequest_analysisId_requestedById_status_idx" ON "curricular"."AnalysisDeletionRequest"("analysisId", "requestedById", "status");

-- CreateIndex
CREATE INDEX "AnalysisDeletionRequest_organizationId_idx" ON "curricular"."AnalysisDeletionRequest"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "UploadedDocument_analysisId_key" ON "curricular"."UploadedDocument"("analysisId");

-- CreateIndex
CREATE INDEX "UploadedDocument_deleteAfter_idx" ON "curricular"."UploadedDocument"("deleteAfter");

-- CreateIndex
CREATE INDEX "UploadedDocument_organizationId_idx" ON "curricular"."UploadedDocument"("organizationId");

-- CreateIndex
CREATE INDEX "AnalyzedSubject_analysisId_period_sortIndex_idx" ON "curricular"."AnalyzedSubject"("analysisId", "period", "sortIndex");

-- CreateIndex
CREATE INDEX "AnalyzedSubject_organizationId_idx" ON "curricular"."AnalyzedSubject"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "AnalyzedSubject_analysisId_rowHash_key" ON "curricular"."AnalyzedSubject"("analysisId", "rowHash");

-- CreateIndex
CREATE INDEX "SemesterProjection_organizationId_idx" ON "curricular"."SemesterProjection"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "SemesterProjection_analysisId_index_key" ON "curricular"."SemesterProjection"("analysisId", "index");

-- CreateIndex
CREATE INDEX "ProjectionSubject_organizationId_idx" ON "curricular"."ProjectionSubject"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "ProjectionSubject_projectionId_subjectId_key" ON "curricular"."ProjectionSubject"("projectionId", "subjectId");

-- CreateIndex
CREATE INDEX "DocumentClaim_analysisId_idx" ON "curricular"."DocumentClaim"("analysisId");

-- CreateIndex
CREATE INDEX "DocumentClaim_organizationId_idx" ON "curricular"."DocumentClaim"("organizationId");

-- CreateIndex
CREATE INDEX "AnalysisWarning_analysisId_resolvedAt_idx" ON "curricular"."AnalysisWarning"("analysisId", "resolvedAt");

-- CreateIndex
CREATE INDEX "AnalysisWarning_organizationId_idx" ON "curricular"."AnalysisWarning"("organizationId");

-- CreateIndex
CREATE INDEX "ManualCorrection_analysisId_createdAt_idx" ON "curricular"."ManualCorrection"("analysisId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "ManualCorrection_organizationId_idx" ON "curricular"."ManualCorrection"("organizationId");

-- CreateIndex
CREATE INDEX "AIExtraction_analysisId_idx" ON "curricular"."AIExtraction"("analysisId");

-- CreateIndex
CREATE INDEX "AIExtraction_organizationId_idx" ON "curricular"."AIExtraction"("organizationId");

-- CreateIndex
CREATE INDEX "AIReview_analysisId_idx" ON "curricular"."AIReview"("analysisId");

-- CreateIndex
CREATE INDEX "AIReview_organizationId_idx" ON "curricular"."AIReview"("organizationId");

-- CreateIndex
CREATE INDEX "AIUsage_createdAt_idx" ON "curricular"."AIUsage"("createdAt");

-- CreateIndex
CREATE INDEX "AIUsage_analysisId_idx" ON "curricular"."AIUsage"("analysisId");

-- CreateIndex
CREATE INDEX "AIUsage_organizationId_idx" ON "curricular"."AIUsage"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "OpenAIIntegration_organizationId_key" ON "curricular"."OpenAIIntegration"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "RuleSetVersion_organizationId_version_key" ON "curricular"."RuleSetVersion"("organizationId", "version");

-- CreateIndex
CREATE INDEX "SystemRule_organizationId_idx" ON "curricular"."SystemRule"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "SystemRule_ruleSetVersionId_key_key" ON "curricular"."SystemRule"("ruleSetVersionId", "key");

-- CreateIndex
CREATE UNIQUE INDEX "CommercialGrade_storageKey_key" ON "curricular"."CommercialGrade"("storageKey");

-- CreateIndex
CREATE INDEX "CommercialGrade_uploadedById_idx" ON "curricular"."CommercialGrade"("uploadedById");

-- CreateIndex
CREATE INDEX "CommercialGrade_courseName_idx" ON "curricular"."CommercialGrade"("courseName");

-- CreateIndex
CREATE INDEX "CommercialGrade_degree_idx" ON "curricular"."CommercialGrade"("degree");

-- CreateIndex
CREATE INDEX "CommercialGrade_knowledgeArea_idx" ON "curricular"."CommercialGrade"("knowledgeArea");

-- CreateIndex
CREATE INDEX "CommercialGrade_durationSemesters_idx" ON "curricular"."CommercialGrade"("durationSemesters");

-- CreateIndex
CREATE INDEX "CommercialGrade_createdAt_idx" ON "curricular"."CommercialGrade"("createdAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "CommercialGrade_organizationId_contentHash_key" ON "curricular"."CommercialGrade"("organizationId", "contentHash");

-- CreateIndex
CREATE UNIQUE INDEX "CommercialGrade_organizationId_catalogKey_key" ON "curricular"."CommercialGrade"("organizationId", "catalogKey");

-- CreateIndex
CREATE INDEX "AcademicGridReview_enrollmentId_idx" ON "curricular"."AcademicGridReview"("enrollmentId");

-- CreateIndex
CREATE INDEX "AcademicGridReview_createdById_createdAt_idx" ON "curricular"."AcademicGridReview"("createdById", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicGridReview_rgm_createdAt_idx" ON "curricular"."AcademicGridReview"("rgm", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicGridReview_studentName_createdAt_idx" ON "curricular"."AcademicGridReview"("studentName", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicGridReview_organizationId_idx" ON "curricular"."AcademicGridReview"("organizationId");

-- CreateIndex
CREATE INDEX "AcademicGridCorrection_reviewId_createdAt_idx" ON "curricular"."AcademicGridCorrection"("reviewId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicGridCorrection_userId_createdAt_idx" ON "curricular"."AcademicGridCorrection"("userId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicGridCorrection_organizationId_idx" ON "curricular"."AcademicGridCorrection"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "StudentEnrollment_currentVersionId_key" ON "curricular"."StudentEnrollment"("currentVersionId");

-- CreateIndex
CREATE INDEX "StudentEnrollment_studentUserId_idx" ON "curricular"."StudentEnrollment"("studentUserId");

-- CreateIndex
CREATE INDEX "StudentEnrollment_ownerId_createdAt_idx" ON "curricular"."StudentEnrollment"("ownerId", "createdAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "StudentEnrollment_organizationId_rgm_key" ON "curricular"."StudentEnrollment"("organizationId", "rgm");

-- CreateIndex
CREATE INDEX "StudentDeletionRequest_status_createdAt_idx" ON "curricular"."StudentDeletionRequest"("status", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "StudentDeletionRequest_enrollmentId_status_idx" ON "curricular"."StudentDeletionRequest"("enrollmentId", "status");

-- CreateIndex
CREATE INDEX "StudentDeletionRequest_organizationId_idx" ON "curricular"."StudentDeletionRequest"("organizationId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisVersion_preferredSourceId_idx" ON "curricular"."AcademicAnalysisVersion"("preferredSourceId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisVersion_enrollmentId_createdAt_idx" ON "curricular"."AcademicAnalysisVersion"("enrollmentId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicAnalysisVersion_reviewId_idx" ON "curricular"."AcademicAnalysisVersion"("reviewId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisVersion_actorUserId_idx" ON "curricular"."AcademicAnalysisVersion"("actorUserId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisVersion_previousVersionId_idx" ON "curricular"."AcademicAnalysisVersion"("previousVersionId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisVersion_organizationId_idx" ON "curricular"."AcademicAnalysisVersion"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "AcademicAnalysisVersion_enrollmentId_version_key" ON "curricular"."AcademicAnalysisVersion"("enrollmentId", "version");

-- CreateIndex
CREATE INDEX "AcademicAnalysisSource_enrollmentId_normalizedContentHash_s_idx" ON "curricular"."AcademicAnalysisSource"("enrollmentId", "normalizedContentHash", "status");

-- CreateIndex
CREATE INDEX "AcademicAnalysisSource_enrollmentId_createdAt_idx" ON "curricular"."AcademicAnalysisSource"("enrollmentId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicAnalysisSource_actorUserId_idx" ON "curricular"."AcademicAnalysisSource"("actorUserId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisSource_versionId_idx" ON "curricular"."AcademicAnalysisSource"("versionId");

-- CreateIndex
CREATE INDEX "AcademicAnalysisSource_deleteAfter_idx" ON "curricular"."AcademicAnalysisSource"("deleteAfter");

-- CreateIndex
CREATE INDEX "AcademicAnalysisSource_organizationId_idx" ON "curricular"."AcademicAnalysisSource"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "AcademicAnalysisSource_enrollmentId_sourceFileHash_key" ON "curricular"."AcademicAnalysisSource"("enrollmentId", "sourceFileHash");

-- CreateIndex
CREATE UNIQUE INDEX "AcademicRequest_protocol_key" ON "curricular"."AcademicRequest"("protocol");

-- CreateIndex
CREATE INDEX "AcademicRequest_status_createdAt_idx" ON "curricular"."AcademicRequest"("status", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "AcademicRequest_actorUserId_idx" ON "curricular"."AcademicRequest"("actorUserId");

-- CreateIndex
CREATE INDEX "AcademicRequest_previousRequestId_idx" ON "curricular"."AcademicRequest"("previousRequestId");

-- CreateIndex
CREATE INDEX "AcademicRequest_organizationId_idx" ON "curricular"."AcademicRequest"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "AcademicRequest_sourceDocumentId_attempt_key" ON "curricular"."AcademicRequest"("sourceDocumentId", "attempt");

-- AddForeignKey
ALTER TABLE "curricular"."AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."CurricularAnalysis" ADD CONSTRAINT "CurricularAnalysis_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."CurricularAnalysis" ADD CONSTRAINT "CurricularAnalysis_enrollmentUpdatedById_fkey" FOREIGN KEY ("enrollmentUpdatedById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."CurricularAnalysis" ADD CONSTRAINT "CurricularAnalysis_reanalysisOfId_fkey" FOREIGN KEY ("reanalysisOfId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."CurricularAnalysis" ADD CONSTRAINT "CurricularAnalysis_ruleSetVersionId_fkey" FOREIGN KEY ("ruleSetVersionId") REFERENCES "curricular"."RuleSetVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."PushSubscription" ADD CONSTRAINT "PushSubscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "curricular"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalysisDeletionRequest" ADD CONSTRAINT "AnalysisDeletionRequest_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalysisDeletionRequest" ADD CONSTRAINT "AnalysisDeletionRequest_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "curricular"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalysisDeletionRequest" ADD CONSTRAINT "AnalysisDeletionRequest_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."UploadedDocument" ADD CONSTRAINT "UploadedDocument_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalyzedSubject" ADD CONSTRAINT "AnalyzedSubject_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."SemesterProjection" ADD CONSTRAINT "SemesterProjection_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."ProjectionSubject" ADD CONSTRAINT "ProjectionSubject_projectionId_fkey" FOREIGN KEY ("projectionId") REFERENCES "curricular"."SemesterProjection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."ProjectionSubject" ADD CONSTRAINT "ProjectionSubject_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "curricular"."AnalyzedSubject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."DocumentClaim" ADD CONSTRAINT "DocumentClaim_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalysisWarning" ADD CONSTRAINT "AnalysisWarning_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalysisWarning" ADD CONSTRAINT "AnalysisWarning_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "curricular"."AnalyzedSubject"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AnalysisWarning" ADD CONSTRAINT "AnalysisWarning_resolvedById_fkey" FOREIGN KEY ("resolvedById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."ManualCorrection" ADD CONSTRAINT "ManualCorrection_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."ManualCorrection" ADD CONSTRAINT "ManualCorrection_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "curricular"."AnalyzedSubject"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."ManualCorrection" ADD CONSTRAINT "ManualCorrection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AIExtraction" ADD CONSTRAINT "AIExtraction_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AIReview" ADD CONSTRAINT "AIReview_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AIUsage" ADD CONSTRAINT "AIUsage_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "curricular"."CurricularAnalysis"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."OpenAIIntegration" ADD CONSTRAINT "OpenAIIntegration_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."OpenAIIntegration" ADD CONSTRAINT "OpenAIIntegration_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."RuleSetVersion" ADD CONSTRAINT "RuleSetVersion_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."SystemRule" ADD CONSTRAINT "SystemRule_ruleSetVersionId_fkey" FOREIGN KEY ("ruleSetVersionId") REFERENCES "curricular"."RuleSetVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."CommercialGrade" ADD CONSTRAINT "CommercialGrade_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicGridReview" ADD CONSTRAINT "AcademicGridReview_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicGridReview" ADD CONSTRAINT "AcademicGridReview_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "curricular"."StudentEnrollment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicGridCorrection" ADD CONSTRAINT "AcademicGridCorrection_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "curricular"."AcademicGridReview"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicGridCorrection" ADD CONSTRAINT "AcademicGridCorrection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."StudentEnrollment" ADD CONSTRAINT "StudentEnrollment_studentUserId_fkey" FOREIGN KEY ("studentUserId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."StudentEnrollment" ADD CONSTRAINT "StudentEnrollment_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."StudentEnrollment" ADD CONSTRAINT "StudentEnrollment_currentVersionId_fkey" FOREIGN KEY ("currentVersionId") REFERENCES "curricular"."AcademicAnalysisVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."StudentDeletionRequest" ADD CONSTRAINT "StudentDeletionRequest_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "curricular"."StudentEnrollment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."StudentDeletionRequest" ADD CONSTRAINT "StudentDeletionRequest_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "curricular"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."StudentDeletionRequest" ADD CONSTRAINT "StudentDeletionRequest_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "curricular"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisVersion" ADD CONSTRAINT "AcademicAnalysisVersion_preferredSourceId_fkey" FOREIGN KEY ("preferredSourceId") REFERENCES "curricular"."AcademicAnalysisSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisVersion" ADD CONSTRAINT "AcademicAnalysisVersion_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "curricular"."StudentEnrollment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisVersion" ADD CONSTRAINT "AcademicAnalysisVersion_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "curricular"."AcademicGridReview"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisVersion" ADD CONSTRAINT "AcademicAnalysisVersion_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisVersion" ADD CONSTRAINT "AcademicAnalysisVersion_previousVersionId_fkey" FOREIGN KEY ("previousVersionId") REFERENCES "curricular"."AcademicAnalysisVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisSource" ADD CONSTRAINT "AcademicAnalysisSource_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "curricular"."StudentEnrollment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisSource" ADD CONSTRAINT "AcademicAnalysisSource_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicAnalysisSource" ADD CONSTRAINT "AcademicAnalysisSource_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "curricular"."AcademicAnalysisVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicRequest" ADD CONSTRAINT "AcademicRequest_sourceDocumentId_fkey" FOREIGN KEY ("sourceDocumentId") REFERENCES "curricular"."AcademicAnalysisSource"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicRequest" ADD CONSTRAINT "AcademicRequest_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "curricular"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "curricular"."AcademicRequest" ADD CONSTRAINT "AcademicRequest_previousRequestId_fkey" FOREIGN KEY ("previousRequestId") REFERENCES "curricular"."AcademicRequest"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Tenant integrity --------------------------------------------------------------------------------
create function private.curricular_tenant_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  sentinel constant uuid := '00000000-0000-0000-0000-000000000000';
  new_data jsonb := to_jsonb(new);
  old_data jsonb := case when tg_op = 'UPDATE' then to_jsonb(old) else null end;
  i integer := 0;
  ref text;
  parent_org uuid;
  inherited uuid;
begin
  if tg_op = 'UPDATE' and new."organizationId" <> old."organizationId" then
    raise exception 'Organization of % cannot change', tg_table_name using errcode = '42501';
  end if;
  while i < tg_nargs loop
    ref := new_data ->> tg_argv[i + 1];
    if ref is not null and (old_data is null or ref is distinct from old_data ->> tg_argv[i + 1]) then
      execute format('select "organizationId" from curricular.%I where id = $1::uuid', tg_argv[i]) into parent_org using ref;
      if parent_org is not null then
        if inherited is null then
          inherited := parent_org;
        elsif inherited <> parent_org then
          raise exception 'Cross-organization reference in %', tg_table_name using errcode = '42501';
        end if;
      end if;
    end if;
    i := i + 2;
  end loop;
  if new."organizationId" = sentinel then
    if inherited is null then
      raise exception 'Organization required for %', tg_table_name using errcode = '23502';
    end if;
    new."organizationId" := inherited;
  elsif inherited is not null and inherited <> new."organizationId" then
    raise exception 'Cross-organization reference in %', tg_table_name using errcode = '42501';
  end if;
  return new;
end $$;
revoke all on function private.curricular_tenant_guard() from public, anon, authenticated, service_role;

create trigger tenant_guard before insert or update on curricular."User"
for each row execute function private.curricular_tenant_guard();
alter table curricular."User" add constraint "User_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."User" enable row level security;
create trigger tenant_guard before insert or update on curricular."AuditLog"
for each row execute function private.curricular_tenant_guard('User', 'userId');
alter table curricular."AuditLog" add constraint "AuditLog_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AuditLog" enable row level security;
create trigger tenant_guard before insert or update on curricular."CurricularAnalysis"
for each row execute function private.curricular_tenant_guard('User', 'createdById', 'User', 'enrollmentUpdatedById', 'CurricularAnalysis', 'reanalysisOfId', 'RuleSetVersion', 'ruleSetVersionId');
alter table curricular."CurricularAnalysis" add constraint "CurricularAnalysis_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."CurricularAnalysis" enable row level security;
create trigger tenant_guard before insert or update on curricular."PushSubscription"
for each row execute function private.curricular_tenant_guard('User', 'userId');
alter table curricular."PushSubscription" add constraint "PushSubscription_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."PushSubscription" enable row level security;
create trigger tenant_guard before insert or update on curricular."AnalysisDeletionRequest"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId', 'User', 'requestedById', 'User', 'reviewedById');
alter table curricular."AnalysisDeletionRequest" add constraint "AnalysisDeletionRequest_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AnalysisDeletionRequest" enable row level security;
create trigger tenant_guard before insert or update on curricular."UploadedDocument"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."UploadedDocument" add constraint "UploadedDocument_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."UploadedDocument" enable row level security;
create trigger tenant_guard before insert or update on curricular."AnalyzedSubject"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."AnalyzedSubject" add constraint "AnalyzedSubject_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AnalyzedSubject" enable row level security;
create trigger tenant_guard before insert or update on curricular."SemesterProjection"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."SemesterProjection" add constraint "SemesterProjection_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."SemesterProjection" enable row level security;
create trigger tenant_guard before insert or update on curricular."ProjectionSubject"
for each row execute function private.curricular_tenant_guard('SemesterProjection', 'projectionId', 'AnalyzedSubject', 'subjectId');
alter table curricular."ProjectionSubject" add constraint "ProjectionSubject_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."ProjectionSubject" enable row level security;
create trigger tenant_guard before insert or update on curricular."DocumentClaim"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."DocumentClaim" add constraint "DocumentClaim_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."DocumentClaim" enable row level security;
create trigger tenant_guard before insert or update on curricular."AnalysisWarning"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId', 'AnalyzedSubject', 'subjectId', 'User', 'resolvedById');
alter table curricular."AnalysisWarning" add constraint "AnalysisWarning_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AnalysisWarning" enable row level security;
create trigger tenant_guard before insert or update on curricular."ManualCorrection"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId', 'AnalyzedSubject', 'subjectId', 'User', 'userId');
alter table curricular."ManualCorrection" add constraint "ManualCorrection_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."ManualCorrection" enable row level security;
create trigger tenant_guard before insert or update on curricular."AIExtraction"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."AIExtraction" add constraint "AIExtraction_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AIExtraction" enable row level security;
create trigger tenant_guard before insert or update on curricular."AIReview"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."AIReview" add constraint "AIReview_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AIReview" enable row level security;
create trigger tenant_guard before insert or update on curricular."AIUsage"
for each row execute function private.curricular_tenant_guard('CurricularAnalysis', 'analysisId');
alter table curricular."AIUsage" add constraint "AIUsage_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AIUsage" enable row level security;
create trigger tenant_guard before insert or update on curricular."OpenAIIntegration"
for each row execute function private.curricular_tenant_guard('User', 'createdById', 'User', 'updatedById');
alter table curricular."OpenAIIntegration" add constraint "OpenAIIntegration_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."OpenAIIntegration" enable row level security;
create trigger tenant_guard before insert or update on curricular."RuleSetVersion"
for each row execute function private.curricular_tenant_guard('User', 'createdById');
alter table curricular."RuleSetVersion" add constraint "RuleSetVersion_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."RuleSetVersion" enable row level security;
create trigger tenant_guard before insert or update on curricular."SystemRule"
for each row execute function private.curricular_tenant_guard('RuleSetVersion', 'ruleSetVersionId');
alter table curricular."SystemRule" add constraint "SystemRule_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."SystemRule" enable row level security;
create trigger tenant_guard before insert or update on curricular."SystemSetting"
for each row execute function private.curricular_tenant_guard();
alter table curricular."SystemSetting" add constraint "SystemSetting_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."SystemSetting" enable row level security;
create trigger tenant_guard before insert or update on curricular."CommercialGrade"
for each row execute function private.curricular_tenant_guard('User', 'uploadedById');
alter table curricular."CommercialGrade" add constraint "CommercialGrade_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."CommercialGrade" enable row level security;
create trigger tenant_guard before insert or update on curricular."AcademicGridReview"
for each row execute function private.curricular_tenant_guard('User', 'createdById', 'StudentEnrollment', 'enrollmentId');
alter table curricular."AcademicGridReview" add constraint "AcademicGridReview_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AcademicGridReview" enable row level security;
create trigger tenant_guard before insert or update on curricular."AcademicGridCorrection"
for each row execute function private.curricular_tenant_guard('AcademicGridReview', 'reviewId', 'User', 'userId');
alter table curricular."AcademicGridCorrection" add constraint "AcademicGridCorrection_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AcademicGridCorrection" enable row level security;
create trigger tenant_guard before insert or update on curricular."StudentEnrollment"
for each row execute function private.curricular_tenant_guard('User', 'studentUserId', 'User', 'ownerId', 'AcademicAnalysisVersion', 'currentVersionId');
alter table curricular."StudentEnrollment" add constraint "StudentEnrollment_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."StudentEnrollment" enable row level security;
create trigger tenant_guard before insert or update on curricular."StudentDeletionRequest"
for each row execute function private.curricular_tenant_guard('StudentEnrollment', 'enrollmentId', 'User', 'requestedById', 'User', 'reviewedById');
alter table curricular."StudentDeletionRequest" add constraint "StudentDeletionRequest_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."StudentDeletionRequest" enable row level security;
create trigger tenant_guard before insert or update on curricular."AcademicAnalysisVersion"
for each row execute function private.curricular_tenant_guard('AcademicAnalysisSource', 'preferredSourceId', 'StudentEnrollment', 'enrollmentId', 'AcademicGridReview', 'reviewId', 'User', 'actorUserId', 'AcademicAnalysisVersion', 'previousVersionId');
alter table curricular."AcademicAnalysisVersion" add constraint "AcademicAnalysisVersion_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AcademicAnalysisVersion" enable row level security;
create trigger tenant_guard before insert or update on curricular."AcademicAnalysisSource"
for each row execute function private.curricular_tenant_guard('StudentEnrollment', 'enrollmentId', 'User', 'actorUserId', 'AcademicAnalysisVersion', 'versionId');
alter table curricular."AcademicAnalysisSource" add constraint "AcademicAnalysisSource_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AcademicAnalysisSource" enable row level security;
create trigger tenant_guard before insert or update on curricular."AcademicRequest"
for each row execute function private.curricular_tenant_guard('AcademicAnalysisSource', 'sourceDocumentId', 'User', 'actorUserId', 'AcademicRequest', 'previousRequestId');
alter table curricular."AcademicRequest" add constraint "AcademicRequest_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;
alter table curricular."AcademicRequest" enable row level security;
alter table curricular."User" add constraint "User_authUser_fkey" foreign key ("authUserId") references auth.users(id) on delete cascade;
create index "User_authUserId_idx" on curricular."User"("authUserId");

-- Not exposed through the Data API: no policies, no privileges for API roles.
revoke all on schema curricular from public, anon, authenticated;
revoke all on all tables in schema curricular from public, anon, authenticated;
revoke all on all sequences in schema curricular from public, anon, authenticated;
