// Generates supabase/schemas/04_curricular.sql from web/prisma/schema.prisma.
// Prisma is only the query client; Supabase migrations own the database. After running this,
// `npm run db:sync` turns the declarative file into a migration.
//
// Every model has "organizationId". A trigger derives it from the referenced rows (nested writes)
// and rejects rows that reference another organization, so tenant isolation does not depend on
// each query remembering a filter.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const schemaPath = `${root}web/prisma/schema.prisma`;
const schema = readFileSync(schemaPath, "utf8");

const ddl = execFileSync("npx", ["prisma", "migrate", "diff", "--from-empty", "--to-schema", "prisma/schema.prisma", "--script"], {
  cwd: `${root}web`,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "inherit"],
});
const tables = ddl.slice(ddl.indexOf("-- CreateSchema")).trimEnd();

// model -> [[parentModel, fkField], ...] from @relation(fields: [...], references: [id])
const references = new Map();
for (const match of schema.matchAll(/^model (\w+) \{([\s\S]*?)^\}/gm)) {
  const [, model, body] = match;
  const refs = [];
  for (const line of body.split("\n")) {
    const relation = line.match(/^\s+\w+\s+(\w+)\??\s+@relation\((?:"\w+",\s*)?fields: \[(\w+)\], references: \[id\]/);
    if (relation) refs.push([relation[1], relation[2]]);
  }
  references.set(model, refs);
}

const guard = `-- Tenant integrity --------------------------------------------------------------------------------
create function private.curricular_tenant_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  sentinel constant uuid := '00000000-0000-0000-0000-000000000000';
  new_data jsonb := to_jsonb(new);
  old_data jsonb := case when tg_op = 'UPDATE' then to_jsonb(old) else null end;
  i integer := 0;
  ref text;
  parent_org uuid;
  inherited uuid;
begin
  if tg_op = 'UPDATE' and new."organizationId" <> old."organizationId" then
    raise exception 'Organization of % cannot change', tg_table_name using errcode = '42501';
  end if;
  while i < tg_nargs loop
    ref := new_data ->> tg_argv[i + 1];
    if ref is not null and (old_data is null or ref is distinct from old_data ->> tg_argv[i + 1]) then
      execute format('select "organizationId" from curricular.%I where id = $1::uuid', tg_argv[i]) into parent_org using ref;
      if parent_org is not null then
        if inherited is null then
          inherited := parent_org;
        elsif inherited <> parent_org then
          raise exception 'Cross-organization reference in %', tg_table_name using errcode = '42501';
        end if;
      end if;
    end if;
    i := i + 2;
  end loop;
  if new."organizationId" = sentinel then
    if inherited is null then
      raise exception 'Organization required for %', tg_table_name using errcode = '23502';
    end if;
    new."organizationId" := inherited;
  elsif inherited is not null and inherited <> new."organizationId" then
    raise exception 'Cross-organization reference in %', tg_table_name using errcode = '42501';
  end if;
  return new;
end $$;
revoke all on function private.curricular_tenant_guard() from public, anon, authenticated, service_role;
`;

const perTable = [];
for (const [model, refs] of references) {
  const args = refs.map(([parent, field]) => `'${parent}', '${field}'`).join(", ");
  perTable.push(
    `create trigger tenant_guard before insert or update on curricular."${model}"\nfor each row execute function private.curricular_tenant_guard(${args});`,
    `alter table curricular."${model}" add constraint "${model}_organization_fkey" foreign key ("organizationId") references public.organizations(id) on delete cascade;`,
    `alter table curricular."${model}" enable row level security;`
  );
}

const output = `-- Curricular analysis module. GENERATED by scripts/curricular-schema.mjs from web/prisma/schema.prisma.
-- Do not edit by hand: change the Prisma schema, rerun the script and then \`npm run db:sync\`.

${tables}

${guard}
${perTable.join("\n")}
alter table curricular."User" add constraint "User_authUser_fkey" foreign key ("authUserId") references auth.users(id) on delete cascade;

-- Regras que o Prisma não expressa (herdadas do sistema de análise curricular).
-- Só uma atualização em processamento por matrícula, mesmo com várias instâncias do app.
create unique index "AcademicAnalysisSource_one_processing" on curricular."AcademicAnalysisSource" ("enrollmentId") where status = 'PROCESSING';
alter table curricular."AcademicAnalysisSource" add constraint "AcademicAnalysisSource_status_check" check (status in ('PROCESSING', 'COMPLETED', 'FAILED'));
alter table curricular."AcademicAnalysisVersion" add constraint "AcademicAnalysisVersion_positive_version" check (version > 0);
alter table curricular."AcademicRequest" add constraint "AcademicRequest_attempt_positive" check (attempt > 0);
create index "User_authUserId_idx" on curricular."User"("authUserId");

-- Not exposed through the Data API: no policies, no privileges for API roles.
revoke all on schema curricular from public, anon, authenticated;
revoke all on all tables in schema curricular from public, anon, authenticated;
revoke all on all sequences in schema curricular from public, anon, authenticated;
`;
writeFileSync(`${root}supabase/schemas/04_curricular.sql`, output);
console.log(`supabase/schemas/04_curricular.sql: ${references.size} tables`);
